name: local_auth_android
publish_to: none
description: Android implementation of the local_auth plugin.
repository: https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+local_auth%22
version: 1.0.49

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

flutter:
  plugin:
    implements: local_auth
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
        dartPluginClass: LocalAuthAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle:
    git: https://github.com/kumsumit/flutter_plugin_android_lifecycle.git
  intl: ">=0.20.2 <0.21.0"
  local_auth_platform_interface: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  pigeon: ^25.3.2

topics:
  - authentication
  - biometrics
  - local-auth
